language: ruby
rvm:
  - 2.4.3
services:
  - postgresql
cache: bundler
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  api_key:
    secure: kkMA4OR9RKyIGYaflL4YSPVsZSKgrenOEgXGDSP/XQoqp0eRSGlf2N0ulLbqJMQcTTqiDxtQMsW43nKlGMDm4MsFjeMgYfsKYVnh0paEptsWfs+1TGtq87uhNcKTWE6VCXvgQuLXs+eO2fnH6eVgvGTxMaR0CwOr5vThFE6uXBEYLS55rAKqtiNpK6v89T15cLezRotCFKuO6dpr8HUOU+LKOBueNAh4LF/FJSDYX+9dwg+ZdseZqzh9kXpLmVDNwOmTaokj9Q7CYfgro+XZ4tCEeM6RAjI4KMBcJeU7Jb9IYP5W8fDabGai/rL8+xHPDtdGWjURLdh8Gbkf9nbO9myFx/eqls4Sb6x2m76a2+R+ssDqnLqCNB41CO6VvjpHH47IB0th8xu46lb+famzVWQE0fe5mfJkzNye9JjPqNSB87oj4adDIc1r+zgecadMHCkcSKaispiLB4m1+G2a4qlZRm/lLwTp9uLjazALEDjAy53rEPG1ecf+necebMWWSssKnI/ainCPx3kuIgo47Df7EEu9tYQm4qYeIfDiWAv+xDAGGEXLg8IRCneCJbfXrE3OM7Ys3AZ1XRTseV1IAxclNcyuxijFMipSJnv2CAPbQX2eMxVqAExGZ3RF6L7hlDbi89qYCFWRtBujaLLfVMb51RNm8h2yD+2uUu0UJE8=
  app: aqueous-retreat-96876
  run:
    - "rake db:migrate"
